name: Package and Release Conda Environment

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0, v2.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.10.8'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3  # Updated to v3
      with:
        miniforge-version: "22.11.1-4"  # 指定一个已知的稳定版本
        python-version: '3.10'
        auto-update: true  # 允许自动更新

    - name: Create and activate conda environment
      run: |
        conda create --name VisRAG python=3.10.8 -y
        source activate VisRAG
        conda install -c nvidia/label/cuda-11.8.0 cuda-toolkit -y

    - name: Install pip dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .
        cd timm_modified
        pip install -e .
        cd ..

    - name: Package the environment with conda-pack
      run: |
        pip install conda-pack
        conda pack -n VisRAG -o VisRAG_env.tar.gz

    - name: Upload environment to GitHub Release
      uses: ncipollo/release-action@v1.11.7  # 使用已发布的最新版本
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: VisRAG Environment for v${{ github.ref_name }}
        files: VisRAG_env.tar.gz
