name: Package and Release Conda Environment

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # 例如，v1.0, v2.0 等

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出存储库
      uses: actions/checkout@v4  # 使用最新的v4版本

    - name: 创建 /mnt/miniconda 目录并设置权限
      run: |
        sudo mkdir -p /mnt/miniconda
        sudo chmod 777 /mnt/miniconda
        ls -ld /mnt/miniconda

    - name: 下载 Miniconda 安装脚本
      run: |
        wget -P /mnt/miniconda https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

    - name: 安装 Miniconda
      run: |
        bash /mnt/miniconda/Miniconda3-latest-Linux-x86_64.sh -b -p /mnt/miniconda/miniconda3

    - name: 配置 Conda
      run: |
        source /mnt/miniconda/miniconda3/etc/profile.d/conda.sh
        conda init bash

    # - name: 安装 Miniconda
    #   uses: conda-incubator/setup-miniconda@v3
    #   with:
    #     miniforge-variant: Miniforge
    #     python-version: '3.10.8'
    #     base-environment-directory: '/mnt/miniconda'
    #     installer-url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"
        # auto-activate-base: false

    - name: 清理 Docker 和 Conda 缓存
      run: |
        docker system prune -af || true
        conda clean -a -y

    - name: 设置并安装依赖
      run: |
        conda create --prefix /mnt/miniconda/miniconda3/envs/VisRAG python=3.10.8 -y
        conda activate /mnt/miniconda/miniconda3/envs/VisRAG
        # conda init bash
        # source ~/.bashrc
        # conda activate VisRAG
        # source /mnt/miniconda/miniconda3/envs/VisRAG/bin/activate
        conda install -c nvidia/label/cuda-11.8.0 cuda-toolkit -y
        conda install -c conda-forge conda-pack -y
        pip install -r requirements.txt
        pip install .
        cd timm_modified
        pip install .
        cd ..

    - name: 打包 Conda 环境
      run: |
        # conda run -n VisRAG conda pack -n VisRAG -o VisRAG_env.tar.gz
        conda run --prefix /mnt/miniconda/miniconda3/envs/VisRAG conda pack -p /mnt/miniconda/miniconda3/envs/VisRAG -o /mnt/VisRAG_env.tar.gz

    - name: 上传环境到 GitHub Release
      uses: softprops/action-gh-release@v2  # 使用有效的发布 Action 版本
      with:
        tag_name: ${{ github.ref_name }}
        name: VisRAG Environment for ${{ github.ref_name }}
        body: "Conda environment package for version ${{ github.ref_name }}"
        files: /mnt/VisRAG_env.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
