name: Package and Release Conda Environment

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # 例如，v1.0, v2.0 等

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出存储库
      uses: actions/checkout@v4  # 使用最新的v4版本

    - name: 安装 Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge  # 使用 Miniforge 代替 Mambaforge
        python-version: '3.10.8'      # 统一 Python 版本
        auto-update-conda: true        # 自动更新 Conda（可选）
        activate-environment: false    # 手动激活环境

    - name: 创建 conda 环境并安装依赖
      run: |
        conda create --name VisRAG python=3.10.8 -y
        conda activate VisRAG
        conda install -c nvidia/label/cuda-11.8.0 cuda-toolkit -y
        conda install -c conda-forge conda-pack -y
        pip install -r requirements.txt
        pip install -e .
        cd timm_modified
        pip install -e .
        cd ..

    - name: 打包 Conda 环境
      run: |
        conda activate VisRAG
        conda pack -n VisRAG -o VisRAG_env.tar.gz

    - name: 创建 GitHub Release
      uses: ncipollo/release-action@v1  # 使用有效的发布 Action 版本
      with:
        tag: ${{ github.ref_name }}
        name: VisRAG Environment for ${{ github.ref_name }}
        files: VisRAG_env.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
